# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Mikhail\Downloads\Mess_qstackedw\messenger\mmm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: #12181B;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 781, 561))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.logining_p = QtWidgets.QWidget()
        self.logining_p.setObjectName("logining_p")
        self.lineEdit_logID = QtWidgets.QLineEdit(self.logining_p)
        self.lineEdit_logID.setGeometry(QtCore.QRect(260, 160, 221, 41))
        self.lineEdit_logID.setStyleSheet("background-color: #454E56;\n"
"border: 4pх solid #A9A9A90;\n"
"border-radius: 16;\n"
"padding: 4;\n"
"color: white;")
        self.lineEdit_logID.setText("")
        self.lineEdit_logID.setMaxLength(8)
        self.lineEdit_logID.setObjectName("lineEdit_logID")
        self.label_logPas = QtWidgets.QLabel(self.logining_p)
        self.label_logPas.setGeometry(QtCore.QRect(270, 220, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_logPas.setFont(font)
        self.label_logPas.setStyleSheet("color: #BEBFC1;\n"
"font-size: 16px;\n"
"background-color: #2A2E35;")
        self.label_logPas.setObjectName("label_logPas")
        self.label_voiti = QtWidgets.QLabel(self.logining_p)
        self.label_voiti.setGeometry(QtCore.QRect(320, 80, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.label_voiti.setFont(font)
        self.label_voiti.setStyleSheet("color: white;\n"
"font-family: \'Arial\';\n"
"font-size: 40px;\n"
"background-color: #2A2E35;")
        self.label_voiti.setObjectName("label_voiti")
        self.label_nonreg = QtWidgets.QLabel(self.logining_p)
        self.label_nonreg.setGeometry(QtCore.QRect(270, 398, 81, 16))
        self.label_nonreg.setMouseTracking(False)
        self.label_nonreg.setStyleSheet("color: #BEBFC1;\n"
"background-color: #2A2E35;")
        self.label_nonreg.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_nonreg.setObjectName("label_nonreg")
        self.label_logID = QtWidgets.QLabel(self.logining_p)
        self.label_logID.setGeometry(QtCore.QRect(270, 140, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.label_logID.setFont(font)
        self.label_logID.setStyleSheet("QLabel{\n"
"    font-family: \'Arial\';\n"
"    color: #BEBFC1;\n"
"    font-size: 16px;\n"
"    background-color: #2A2E35;\n"
"}\n"
"")
        self.label_logID.setObjectName("label_logID")
        self.lineEdit_logPas = QtWidgets.QLineEdit(self.logining_p)
        self.lineEdit_logPas.setGeometry(QtCore.QRect(260, 240, 221, 41))
        self.lineEdit_logPas.setStyleSheet("background-color: #454E56;\n"
"border: 4pх solid #A9A9A9;\n"
"border-radius: 16;\n"
"padding: 4;\n"
"color: white;")
        self.lineEdit_logPas.setText("")
        self.lineEdit_logPas.setMaxLength(16)
        self.lineEdit_logPas.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_logPas.setDragEnabled(False)
        self.lineEdit_logPas.setObjectName("lineEdit_logPas")
        self.label_error = QtWidgets.QLabel(self.logining_p)
        self.label_error.setGeometry(QtCore.QRect(280, 290, 191, 16))
        self.label_error.setStyleSheet("color: red;\n"
"background-color: #2A2E35;")
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        self.pushButton_reg = QtWidgets.QPushButton(self.logining_p)
        self.pushButton_reg.setGeometry(QtCore.QRect(350, 390, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_reg.setFont(font)
        self.pushButton_reg.setMouseTracking(True)
        self.pushButton_reg.setStyleSheet("padding-bottom: 0;\n"
"border: none;\n"
"color: #30466C;\n"
"background-color: #2A2E35;")
        self.pushButton_reg.setObjectName("pushButton_reg")
        self.pushButton_logIn = QtWidgets.QPushButton(self.logining_p)
        self.pushButton_logIn.setGeometry(QtCore.QRect(300, 320, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_logIn.setFont(font)
        self.pushButton_logIn.setStyleSheet("\n"
"background-color: #09C372;\n"
"border-radius: 8;\n"
"color: white;")
        self.pushButton_logIn.setObjectName("pushButton_logIn")
        self.graphicsView = QtWidgets.QGraphicsView(self.logining_p)
        self.graphicsView.setGeometry(QtCore.QRect(210, 50, 331, 421))
        self.graphicsView.setStyleSheet("border-radius: 48px;\n"
"background-color: #2A2E35;\n"
"box-shadow: -16px black; ")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.raise_()
        self.lineEdit_logID.raise_()
        self.label_logPas.raise_()
        self.label_voiti.raise_()
        self.label_nonreg.raise_()
        self.label_logID.raise_()
        self.lineEdit_logPas.raise_()
        self.label_error.raise_()
        self.pushButton_reg.raise_()
        self.pushButton_logIn.raise_()
        self.stackedWidget.addWidget(self.logining_p)
        self.reg_p = QtWidgets.QWidget()
        self.reg_p.setObjectName("reg_p")
        self.label_registration = QtWidgets.QLabel(self.reg_p)
        self.label_registration.setGeometry(QtCore.QRect(290, 10, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.label_registration.setFont(font)
        self.label_registration.setStyleSheet("color: white;\n"
"font-size: 32px;\n"
"font-family: \'Arial\';\n"
"background-color: #2A2E35;")
        self.label_registration.setObjectName("label_registration")
        self.label_regwarn = QtWidgets.QLabel(self.reg_p)
        self.label_regwarn.setGeometry(QtCore.QRect(260, 340, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_regwarn.setFont(font)
        self.label_regwarn.setStyleSheet("background-color: #2A2E35;\n"
"color: red;")
        self.label_regwarn.setText("")
        self.label_regwarn.setObjectName("label_regwarn")
        self.label_regID = QtWidgets.QLabel(self.reg_p)
        self.label_regID.setGeometry(QtCore.QRect(240, 200, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.label_regID.setFont(font)
        self.label_regID.setStyleSheet("padding: 0;\n"
"font-family: \'Arial\';\n"
"font-size: 12px;\n"
"color: #AFB1B3;\n"
"background-color: #2A2E35;\n"
"")
        self.label_regID.setObjectName("label_regID")
        self.label_regName = QtWidgets.QLabel(self.reg_p)
        self.label_regName.setGeometry(QtCore.QRect(240, 60, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.label_regName.setFont(font)
        self.label_regName.setStyleSheet("padding: 0;\n"
"font-family: \'Arial\';\n"
"font-size: 12px;\n"
"color: #AFB1B3;\n"
"background-color: #2A2E35;")
        self.label_regName.setObjectName("label_regName")
        self.label_regMail = QtWidgets.QLabel(self.reg_p)
        self.label_regMail.setGeometry(QtCore.QRect(240, 130, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.label_regMail.setFont(font)
        self.label_regMail.setStyleSheet("padding: 0;\n"
"font-family: \'Arial\';\n"
"font-size: 12px;\n"
"color: #AFB1B3;\n"
"background-color: #2A2E35;\n"
"")
        self.label_regMail.setObjectName("label_regMail")
        self.label_regPass = QtWidgets.QLabel(self.reg_p)
        self.label_regPass.setGeometry(QtCore.QRect(240, 270, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.label_regPass.setFont(font)
        self.label_regPass.setStyleSheet("padding: 0;\n"
"font-family: \'Arial\';\n"
"font-size: 12px;\n"
"color: #AFB1B3;\n"
"background-color: #2A2E35;")
        self.label_regPass.setObjectName("label_regPass")
        self.pushButton_Registrate = QtWidgets.QPushButton(self.reg_p)
        self.pushButton_Registrate.setGeometry(QtCore.QRect(310, 370, 151, 41))
        self.pushButton_Registrate.setStyleSheet("background-color: #09C372;\n"
"border-radius: 16px;\n"
"color: white;\n"
"font-family: \'Arial\';\n"
"font-size: 14px;\n"
"padding: 4px;")
        self.pushButton_Registrate.setObjectName("pushButton_Registrate")
        self.lineEdit_makeName = QtWidgets.QLineEdit(self.reg_p)
        self.lineEdit_makeName.setGeometry(QtCore.QRect(230, 80, 301, 41))
        self.lineEdit_makeName.setStyleSheet("background-color: #454E56;\n"
"border: 4pх solid #A9A9A9;\n"
"border-radius: 16;\n"
"padding: 4;\n"
"dont-family: \'Arial\';\n"
"font-size: 12px;\n"
"color: white;\n"
"\n"
"")
        self.lineEdit_makeName.setMaxLength(10)
        self.lineEdit_makeName.setObjectName("lineEdit_makeName")
        self.lineEdit_makeID = QtWidgets.QLineEdit(self.reg_p)
        self.lineEdit_makeID.setGeometry(QtCore.QRect(230, 220, 301, 41))
        self.lineEdit_makeID.setStyleSheet("background-color: #454E56;\n"
"border: 4pх solid #A9A9A9;\n"
"border-radius: 16;\n"
"padding: 4;\n"
"dont-family: \'Arial\';\n"
"font-size: 12px;\n"
"color: white;")
        self.lineEdit_makeID.setMaxLength(8)
        self.lineEdit_makeID.setObjectName("lineEdit_makeID")
        self.lineEdit_makeMail = QtWidgets.QLineEdit(self.reg_p)
        self.lineEdit_makeMail.setGeometry(QtCore.QRect(230, 150, 301, 41))
        self.lineEdit_makeMail.setStyleSheet("background-color: #454E56;\n"
"border: 4pх solid #A9A9A9;\n"
"border-radius: 16;\n"
"padding: 4;\n"
"dont-family: \'Arial\';\n"
"font-size: 12px;\n"
"color: white;")
        self.lineEdit_makeMail.setMaxLength(16)
        self.lineEdit_makeMail.setObjectName("lineEdit_makeMail")
        self.lineEdit_makePas = QtWidgets.QLineEdit(self.reg_p)
        self.lineEdit_makePas.setGeometry(QtCore.QRect(230, 290, 301, 41))
        self.lineEdit_makePas.setStyleSheet("background-color: #454E56;\n"
"border: 4pх solid #A9A9A9;\n"
"border-radius: 16;\n"
"padding: 4;\n"
"dont-family: \'Arial\';\n"
"font-size: 12px;\n"
"color: white;")
        self.lineEdit_makePas.setMaxLength(16)
        self.lineEdit_makePas.setObjectName("lineEdit_makePas")
        self.pushButton_backtolog = QtWidgets.QPushButton(self.reg_p)
        self.pushButton_backtolog.setGeometry(QtCore.QRect(10, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.pushButton_backtolog.setFont(font)
        self.pushButton_backtolog.setStyleSheet("background-color: #5088E9;\n"
"border-radius: 16px;\n"
"color: white;\n"
"font-family: \'Arial\';\n"
"font-size: 14px;\n"
"padding: 4px;")
        self.pushButton_backtolog.setObjectName("pushButton_backtolog")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.reg_p)
        self.graphicsView_2.setGeometry(QtCore.QRect(210, 10, 341, 441))
        self.graphicsView_2.setStyleSheet("border-radius: 32px;\n"
"background-color: #2A2E35;")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_2.raise_()
        self.label_registration.raise_()
        self.label_regwarn.raise_()
        self.label_regID.raise_()
        self.label_regName.raise_()
        self.label_regMail.raise_()
        self.label_regPass.raise_()
        self.pushButton_Registrate.raise_()
        self.lineEdit_makeName.raise_()
        self.lineEdit_makeID.raise_()
        self.lineEdit_makeMail.raise_()
        self.lineEdit_makePas.raise_()
        self.pushButton_backtolog.raise_()
        self.stackedWidget.addWidget(self.reg_p)
        self.page_about = QtWidgets.QWidget()
        self.page_about.setObjectName("page_about")
        self.label_about = QtWidgets.QLabel(self.page_about)
        self.label_about.setGeometry(QtCore.QRect(310, 20, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.label_about.setFont(font)
        self.label_about.setStyleSheet("color: white;\n"
"font-size: 32px;\n"
"font-family: \'Arial\';\n"
"background-color: #2A2E35;")
        self.label_about.setObjectName("label_about")
        self.lineEdit_infoName = QtWidgets.QLineEdit(self.page_about)
        self.lineEdit_infoName.setGeometry(QtCore.QRect(250, 90, 301, 41))
        self.lineEdit_infoName.setStyleSheet("background-color: #454E56;\n"
"border: 4pх solid #A9A9A9;\n"
"border-radius: 16;\n"
"padding: 4;\n"
"dont-family: \'Arial\';\n"
"font-size: 12px;\n"
"color: white;\n"
"\n"
"")
        self.lineEdit_infoName.setMaxLength(10)
        self.lineEdit_infoName.setObjectName("lineEdit_infoName")
        self.label_infoName = QtWidgets.QLabel(self.page_about)
        self.label_infoName.setGeometry(QtCore.QRect(260, 70, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.label_infoName.setFont(font)
        self.label_infoName.setStyleSheet("padding: 0;\n"
"font-family: \'Arial\';\n"
"font-size: 12px;\n"
"color: #AFB1B3;\n"
"background-color: #2A2E35;")
        self.label_infoName.setObjectName("label_infoName")
        self.label_infoID = QtWidgets.QLabel(self.page_about)
        self.label_infoID.setGeometry(QtCore.QRect(260, 210, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.label_infoID.setFont(font)
        self.label_infoID.setStyleSheet("padding: 0;\n"
"font-family: \'Arial\';\n"
"font-size: 12px;\n"
"color: #AFB1B3;\n"
"background-color: #2A2E35;\n"
"")
        self.label_infoID.setObjectName("label_infoID")
        self.lineEdit_infoID = QtWidgets.QLineEdit(self.page_about)
        self.lineEdit_infoID.setGeometry(QtCore.QRect(250, 230, 301, 41))
        self.lineEdit_infoID.setStyleSheet("background-color: #454E56;\n"
"border: 4pх solid #A9A9A9;\n"
"border-radius: 16;\n"
"padding: 4;\n"
"dont-family: \'Arial\';\n"
"font-size: 12px;\n"
"color: white;")
        self.lineEdit_infoID.setMaxLength(8)
        self.lineEdit_infoID.setObjectName("lineEdit_infoID")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.page_about)
        self.graphicsView_3.setGeometry(QtCore.QRect(230, 20, 341, 441))
        self.graphicsView_3.setStyleSheet("border-radius: 32px;\n"
"background-color: #2A2E35;\n"
"")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.lineEdit_infoMail = QtWidgets.QLineEdit(self.page_about)
        self.lineEdit_infoMail.setGeometry(QtCore.QRect(250, 160, 301, 41))
        self.lineEdit_infoMail.setStyleSheet("background-color: #454E56;\n"
"border: 4pх solid #A9A9A9;\n"
"border-radius: 16;\n"
"padding: 4;\n"
"dont-family: \'Arial\';\n"
"font-size: 12px;\n"
"color: white;")
        self.lineEdit_infoMail.setMaxLength(16)
        self.lineEdit_infoMail.setObjectName("lineEdit_infoMail")
        self.label_infoPass = QtWidgets.QLabel(self.page_about)
        self.label_infoPass.setGeometry(QtCore.QRect(260, 280, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.label_infoPass.setFont(font)
        self.label_infoPass.setStyleSheet("padding: 0;\n"
"font-family: \'Arial\';\n"
"font-size: 12px;\n"
"color: #AFB1B3;\n"
"background-color: #2A2E35;")
        self.label_infoPass.setObjectName("label_infoPass")
        self.label_infoMail = QtWidgets.QLabel(self.page_about)
        self.label_infoMail.setGeometry(QtCore.QRect(260, 140, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.label_infoMail.setFont(font)
        self.label_infoMail.setStyleSheet("padding: 0;\n"
"font-family: \'Arial\';\n"
"font-size: 12px;\n"
"color: #AFB1B3;\n"
"background-color: #2A2E35;\n"
"")
        self.label_infoMail.setObjectName("label_infoMail")
        self.label_infoWarn = QtWidgets.QLabel(self.page_about)
        self.label_infoWarn.setGeometry(QtCore.QRect(280, 350, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_infoWarn.setFont(font)
        self.label_infoWarn.setStyleSheet("background-color: #2A2E35;\n"
"color: red;")
        self.label_infoWarn.setText("")
        self.label_infoWarn.setObjectName("label_infoWarn")
        self.lineEdit_infoPas = QtWidgets.QLineEdit(self.page_about)
        self.lineEdit_infoPas.setGeometry(QtCore.QRect(250, 300, 301, 41))
        self.lineEdit_infoPas.setStyleSheet("background-color: #454E56;\n"
"border: 4pх solid #A9A9A9;\n"
"border-radius: 16;\n"
"padding: 4;\n"
"dont-family: \'Arial\';\n"
"font-size: 12px;\n"
"color: white;")
        self.lineEdit_infoPas.setMaxLength(16)
        self.lineEdit_infoPas.setObjectName("lineEdit_infoPas")
        self.pushButton_backtomenues_2 = QtWidgets.QPushButton(self.page_about)
        self.pushButton_backtomenues_2.setGeometry(QtCore.QRect(30, 20, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.pushButton_backtomenues_2.setFont(font)
        self.pushButton_backtomenues_2.setStyleSheet("background-color: #5088E9;\n"
"border-radius: 16px;\n"
"color: white;\n"
"font-family: \'Arial\';\n"
"font-size: 14px;\n"
"padding: 4px;")
        self.pushButton_backtomenues_2.setObjectName("pushButton_backtomenues_2")
        self.pushButton_exit = QtWidgets.QPushButton(self.page_about)
        self.pushButton_exit.setGeometry(QtCore.QRect(250, 400, 111, 41))
        self.pushButton_exit.setStyleSheet("background-color: #FF5F5B;\n"
"border-radius: 16px;\n"
"color: white;\n"
"font-family: \'Arial\';\n"
"font-size: 14px;\n"
"padding: 4px;")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.graphicsView_3.raise_()
        self.lineEdit_infoMail.raise_()
        self.label_infoPass.raise_()
        self.label_infoMail.raise_()
        self.lineEdit_infoPas.raise_()
        self.label_infoID.raise_()
        self.label_infoName.raise_()
        self.lineEdit_infoName.raise_()
        self.label_about.raise_()
        self.label_infoWarn.raise_()
        self.lineEdit_infoID.raise_()
        self.pushButton_backtomenues_2.raise_()
        self.pushButton_exit.raise_()
        self.stackedWidget.addWidget(self.page_about)
        self.menues_p = QtWidgets.QWidget()
        self.menues_p.setObjectName("menues_p")
        self.tabWidget = QtWidgets.QTabWidget(self.menues_p)
        self.tabWidget.setGeometry(QtCore.QRect(0, 20, 781, 551))
        self.tabWidget.setStyleSheet("QTabWidget::tab-bar\n"
"{\n"
"    left: 5px;\n"
"    alignment: left;\n"
"    background-color: #3E3E3E;\n"
"}\n"
"QTabBar::bar{\n"
"    background-color: #12181B;\n"
"    font-family: \'Arial\';\n"
"}\n"
"")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_newChat = QtWidgets.QPushButton(self.tab)
        self.pushButton_newChat.setGeometry(QtCore.QRect(600, 460, 161, 41))
        self.pushButton_newChat.setStyleSheet("background-color: #5088E9;\n"
"border-radius: 16px;\n"
"color: white;\n"
"font-size: 16px;")
        self.pushButton_newChat.setObjectName("pushButton_newChat")
        self.listWidget_chats = QtWidgets.QListWidget(self.tab)
        self.listWidget_chats.setGeometry(QtCore.QRect(10, 10, 581, 491))
        self.listWidget_chats.setStyleSheet("background-color: #2A2E35;\n"
"color: white;")
        self.listWidget_chats.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listWidget_chats.setObjectName("listWidget_chats")
        self.pushButton_acc_info = QtWidgets.QPushButton(self.tab)
        self.pushButton_acc_info.setGeometry(QtCore.QRect(600, 10, 161, 41))
        self.pushButton_acc_info.setStyleSheet("background-color: #454E56;\n"
"border-radius: 16px;\n"
"color: white;\n"
"font-size: 16px;")
        self.pushButton_acc_info.setObjectName("pushButton_acc_info")
        self.lineEdit_newlogin = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_newlogin.setGeometry(QtCore.QRect(600, 330, 161, 41))
        self.lineEdit_newlogin.setStyleSheet("background-color: #454E56;\n"
"border: none;\n"
"border-radius: 16px;\n"
"color: white;\n"
"font-size: 12px;\n"
"font-family: \'Arial\';\n"
"")
        self.lineEdit_newlogin.setObjectName("lineEdit_newlogin")
        self.lineEdit_newname = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_newname.setGeometry(QtCore.QRect(600, 280, 161, 41))
        self.lineEdit_newname.setStyleSheet("background-color: #454E56;\n"
"border: none;\n"
"border-radius: 16px;\n"
"color: white;\n"
"font-size: 12px;\n"
"font-family: \'Arial\';")
        self.lineEdit_newname.setObjectName("lineEdit_newname")
        self.lineEdit_newmail = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_newmail.setGeometry(QtCore.QRect(600, 380, 161, 41))
        self.lineEdit_newmail.setStyleSheet("background-color: #454E56;\n"
"border: none;\n"
"border-radius: 16px;\n"
"color: white;\n"
"font-size: 12px;\n"
"font-family: \'Arial\';\n"
"padding-left: 4px;")
        self.lineEdit_newmail.setObjectName("lineEdit_newmail")
        self.label_makenew = QtWidgets.QLabel(self.tab)
        self.label_makenew.setGeometry(QtCore.QRect(610, 250, 151, 31))
        self.label_makenew.setStyleSheet("color: white;\n"
"font-size: 12px;\n"
"font-family: \'Arial\';")
        self.label_makenew.setObjectName("label_makenew")
        self.label_newwarn = QtWidgets.QLabel(self.tab)
        self.label_newwarn.setGeometry(QtCore.QRect(610, 430, 131, 21))
        self.label_newwarn.setStyleSheet("color: red;\n"
"font-family: \'Arial\';")
        self.label_newwarn.setObjectName("label_newwarn")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.tab_2)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 100, 441, 401))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setStyleSheet("background-color: fb5b5d;\n"
"border-radius: 8;\n"
"color: #808080;\n"
"")
        self.calendarWidget.setObjectName("calendarWidget")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 751, 71))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_2.setFont(font)
        self.label_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_2.setStyleSheet("color : white;\n"
"border-radius: 8px;\n"
"background-color: #22222e;\n"
"border: 1px solid #afafaf;")
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setObjectName("label_2")
        self.TaskLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.TaskLineEdit.setGeometry(QtCore.QRect(460, 100, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.TaskLineEdit.setFont(font)
        self.TaskLineEdit.setStyleSheet("color : white;\n"
"background-color: #454E56;\n"
"border-radius: 8px;\n"
"font-family: \'Arial\';")
        self.TaskLineEdit.setObjectName("TaskLineEdit")
        self.tasksListWidget = QtWidgets.QListWidget(self.tab_2)
        self.tasksListWidget.setGeometry(QtCore.QRect(460, 150, 301, 291))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tasksListWidget.setFont(font)
        self.tasksListWidget.setStyleSheet("color : white;\n"
"background-color: #2A2E35;\n"
"border: none;")
        self.tasksListWidget.setObjectName("tasksListWidget")
        self.saveButton = QtWidgets.QPushButton(self.tab_2)
        self.saveButton.setGeometry(QtCore.QRect(460, 450, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("QPushButton{    \n"
"    background-color: #09C372;\n"
"    border: none;\n"
"    border-radius: 8;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #606060\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #DCDCDC\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.addButton = QtWidgets.QPushButton(self.tab_2)
        self.addButton.setGeometry(QtCore.QRect(720, 100, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.addButton.setFont(font)
        self.addButton.setStyleSheet("QPushButton{    \n"
"    background-color: #09C372;\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #606060\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #DCDCDC\n"
"}")
        self.addButton.setObjectName("addButton")
        self.tabWidget.addTab(self.tab_2, "")
        self.stackedWidget.addWidget(self.menues_p)
        self.messenging = QtWidgets.QWidget()
        self.messenging.setObjectName("messenging")
        self.label = QtWidgets.QLabel(self.messenging)
        self.label.setGeometry(QtCore.QRect(60, 20, 181, 21))
        self.label.setStyleSheet("color: white;\n"
"font-size: 24px;")
        self.label.setObjectName("label")
        self.lineEdit_makeMessage = QtWidgets.QLineEdit(self.messenging)
        self.lineEdit_makeMessage.setGeometry(QtCore.QRect(10, 510, 701, 41))
        self.lineEdit_makeMessage.setStyleSheet("background-color: #454E56;\n"
"border: none;\n"
"border-radius: 20px;\n"
"padding-left: 8px;\n"
"color: white;\n"
"font-size: 16px;\n"
"font-family: \'Arial\';")
        self.lineEdit_makeMessage.setObjectName("lineEdit_makeMessage")
        self.pushButton_send = QtWidgets.QPushButton(self.messenging)
        self.pushButton_send.setGeometry(QtCore.QRect(720, 510, 41, 41))
        self.pushButton_send.setStyleSheet("border: none;")
        self.pushButton_send.setText("")
        self.pushButton_send.setObjectName("pushButton_send")
        self.textBrowser = QtWidgets.QTextBrowser(self.messenging)
        self.textBrowser.setGeometry(QtCore.QRect(560, 40, 201, 441))
        self.textBrowser.setStyleSheet("background-color:#2A2E35;\n"
"border-radius: 16px;\n"
"border: none;\n"
"color: white;\n"
"font-family: \'Arial\';\n"
"font-size: 16px;")
        self.textBrowser.setObjectName("textBrowser")
        self.listWidget_messages = QtWidgets.QListWidget(self.messenging)
        self.listWidget_messages.setGeometry(QtCore.QRect(10, 60, 541, 411))
        self.listWidget_messages.setStyleSheet("background-color:#2A2E35;\n"
"border-radius: 16px;\n"
"border: none;\n"
"color: white;\n"
"font-family: \'Arial\';\n"
"font-size: 16px;")
        self.listWidget_messages.setObjectName("listWidget_messages")
        self.pushButton_backtomenues = QtWidgets.QPushButton(self.messenging)
        self.pushButton_backtomenues.setGeometry(QtCore.QRect(10, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.pushButton_backtomenues.setFont(font)
        self.pushButton_backtomenues.setStyleSheet("background-color: #5088E9;\n"
"border-radius: 16px;\n"
"color: white;\n"
"font-family: \'Arial\';\n"
"font-size: 14px;\n"
"padding: 4px;")
        self.pushButton_backtomenues.setObjectName("pushButton_backtomenues")
        self.stackedWidget.addWidget(self.messenging)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_logID.setPlaceholderText(_translate("MainWindow", "Введите ID"))
        self.label_logPas.setText(_translate("MainWindow", "Password"))
        self.label_voiti.setText(_translate("MainWindow", "Войти"))
        self.label_nonreg.setText(_translate("MainWindow", "Нет аккаунта?"))
        self.label_logID.setText(_translate("MainWindow", "Login"))
        self.lineEdit_logPas.setPlaceholderText(_translate("MainWindow", "Введите пароль"))
        self.pushButton_reg.setText(_translate("MainWindow", "Создать аккаунт"))
        self.pushButton_logIn.setText(_translate("MainWindow", "Авторизоваться"))
        self.label_registration.setText(_translate("MainWindow", "Регистрация"))
        self.label_regID.setText(_translate("MainWindow", "Логин"))
        self.label_regName.setText(_translate("MainWindow", "Имя и фамилия"))
        self.label_regMail.setText(_translate("MainWindow", "Почта"))
        self.label_regPass.setText(_translate("MainWindow", "Пароль"))
        self.pushButton_Registrate.setText(_translate("MainWindow", "Зарегистрироваться"))
        self.lineEdit_makeName.setPlaceholderText(_translate("MainWindow", "Введите имя и фамилию*"))
        self.lineEdit_makeID.setPlaceholderText(_translate("MainWindow", "Придумайте логин*"))
        self.lineEdit_makeMail.setPlaceholderText(_translate("MainWindow", "Введите почту"))
        self.lineEdit_makePas.setPlaceholderText(_translate("MainWindow", "Придумайте пароль*"))
        self.pushButton_backtolog.setText(_translate("MainWindow", "< Назад"))
        self.label_about.setText(_translate("MainWindow", "Об аккаунте"))
        self.lineEdit_infoName.setPlaceholderText(_translate("MainWindow", "Введите имя и фамилию*"))
        self.label_infoName.setText(_translate("MainWindow", "Имя и фамилия"))
        self.label_infoID.setText(_translate("MainWindow", "Логин"))
        self.lineEdit_infoID.setPlaceholderText(_translate("MainWindow", "Придумайте логин*"))
        self.lineEdit_infoMail.setPlaceholderText(_translate("MainWindow", "Введите почту"))
        self.label_infoPass.setText(_translate("MainWindow", "Пароль"))
        self.label_infoMail.setText(_translate("MainWindow", "Почта"))
        self.lineEdit_infoPas.setPlaceholderText(_translate("MainWindow", "Придумайте пароль*"))
        self.pushButton_backtomenues_2.setText(_translate("MainWindow", "< Назад"))
        self.pushButton_exit.setText(_translate("MainWindow", "Выход"))
        self.pushButton_newChat.setText(_translate("MainWindow", "Новый контакт"))
        self.pushButton_acc_info.setText(_translate("MainWindow", "Настройки аккаунта"))
        self.lineEdit_newlogin.setPlaceholderText(_translate("MainWindow", "*Введите логин..."))
        self.lineEdit_newname.setPlaceholderText(_translate("MainWindow", "*Введите имя..."))
        self.lineEdit_newmail.setPlaceholderText(_translate("MainWindow", "Введите почту..."))
        self.label_makenew.setText(_translate("MainWindow", "Создать новый диалог"))
        self.label_newwarn.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Сообщения"))
        self.label_2.setText(_translate("MainWindow", "Ежедневник"))
        self.TaskLineEdit.setPlaceholderText(_translate("MainWindow", "Введите задачу..."))
        self.saveButton.setText(_translate("MainWindow", "Сохранить "))
        self.addButton.setText(_translate("MainWindow", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Ежедневник"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.lineEdit_makeMessage.setPlaceholderText(_translate("MainWindow", "Введите сообщение..."))
        self.pushButton_backtomenues.setText(_translate("MainWindow", "<"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
